name: crud_api

services:
  psql:
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - .env
    # environment:
    #   POSTGRES_USER: root
    #   POSTGRES_DB: crud
    networks:
      - db
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - db
networks:
  db:
